export default {
    $schema: 'http://json.schemastore.org/prettierrc',
    semi: true,
    arrowParens: 'always',
    singleQuote: true,
    trailingComma: 'es5',
    bracketSpacing: true,
    htmlWhitespaceSensitivity: 'css',
    insertPragma: false,
    tabWidth: 4,
    useTabs: false,
    vueIndentScriptAndStyle: true,
    endOfLine: 'lf',
    // jsxBracketSameLine: false,
    // jsxSingleQuote: true,
    // proseWrap: 'never',
    // quoteProps: 'as-needed',
}
