import fsp from 'node:fs/promises'
import { URL, fileURLToPath } from 'node:url'

import * as allModules from '../dist'

const modules = Object.keys(allModules).filter(m => m !== '__esModule')

const preset = ({
    '@democrance/utils': modules,
})
const comment = '// This is autogenerated file'
const exports = `export default ${JSON.stringify(preset, null, 4)}`

const pathToLib = fileURLToPath(new URL('../lib', import.meta.url))
const mjs = `${comment}\n${exports}`

await fsp.writeFile(`${pathToLib}/preset/autoImportUtilsPreset.ts`, mjs, 'utf-8')
